
// Kode til dyr
const animals = [
	{
	  dexNumber: "ARC-001",
	  name: "Isbjørn",
	  image: "Images/Images/animals/isbjornen.png",
	  category: "pattedyr",
	  description: "Top rovdyr i Arktis",
	  region: "Arctic",
	  id: "isbjørn",
	  rarity: "rare",
	  link: "learnmore.html",

	  habitat: "Sea ice, Arctic coastlines and cold marine environments.",
	  diet: "Mainly seals, especially ringed seals, but it can also eat birds, eggs, carrion and whale remains.",
	  size: "Adult males can weigh around 350–700 kg, while females are usually smaller.",
	  behaviour: "A solitary and powerful predator that depends heavily on sea ice for hunting.",
	  bestSeason: "Spring and early summer, when sea ice conditions are important for hunting.",
	  bestPlace: "Remote Arctic coastlines, sea ice areas and northern regions.",
	  funFact: "Polar bears have black skin under their white fur, which helps absorb heat from the sun.",
	  conservation: "Vulnerable"
	},
	{
	  dexNumber: "ARC-002",
	  name: "Moskusokse",
	  image: "Images/Images/animals/moskusokse.png",
	  category: "pattedyr",
	  description: "Vejer 180-400 kg.",
	  region: "Arctic",
	  id: "moskusokse",
	  rarity: "rare",
	  link: "learnmore.html",

	  habitat: "Arctic tundra, open valleys, rocky slopes and cold grassland areas.",
	  diet: "Grasses, mosses, lichens, willow, herbs and other tough Arctic plants.",
	  size: "Usually around 180–400 kg.",
	  behaviour: "Lives in groups and can form a defensive circle when threatened by predators.",
	  bestSeason: "Summer and autumn, when they are easier to spot while grazing in open landscapes.",
	  bestPlace: "Open tundra, valleys and fjeld areas with low vegetation.",
	  funFact: "The soft underwool of the musk ox is called qiviut and is one of the warmest natural fibres in the world.",
	  conservation: "Least Concern"
	},
  {
	dexNumber: "ARC-003",
    name: "Polarræv",
    image: "Images/Images/animals/polarrav.png",
    category: "pattedyr",
    description: "To slags ræv. Blåræv og hvidræv",
    region: "Arctic",
    id: "polarræv",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Arctic tundra, coastal areas and rocky landscapes.",
    diet: "Birds, eggs, small mammals, carrion and leftovers from larger predators.",
    size: "Usually 3–8 kg.",
    behaviour: "Highly adaptable, curious and able to survive extreme cold.",
    bestSeason: "Spring and summer, when it is more active around nesting birds.",
    bestPlace: "Open tundra, coastal areas and near bird cliffs.",
    funFact: "The Arctic fox can survive temperatures far below freezing because of its dense winter fur.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-004",
    name: "Rensdyr",
    image: "Images/Images/animals/rensdyr.png",
    category: "pattedyr",
    description: "Hanner vejer op til 300 kg. Renen er den eneste hjort, hvor begge køn bærer gevir",
    region: "Arctic",
    id: "rensdyr",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Tundra, mountains, open heathland and grassy areas.",
    diet: "Lichens, grasses, herbs, leaves and mosses.",
    size: "Large males can weigh up to around 300 kg.",
    behaviour: "Often moves in groups and can travel long distances while feeding.",
    bestSeason: "Summer and autumn.",
    bestPlace: "Open fjeld areas and tundra landscapes.",
    funFact: "Reindeer are the only deer species where both males and females can grow antlers.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-005",
    name: "Polarulv",
    image: "Images/Images/animals/polarulv.png",
    category: "pattedyr",
    description: "Er en underart af grå ulv, som kun findes i Grønland og på Ellesmere Island",
    region: "Arctic",
    id: "polarulv",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "High Arctic tundra, remote valleys, rocky landscapes and polar desert areas.",
    diet: "Musk oxen, Arctic hares, birds, eggs and other available Arctic prey.",
    size: "Usually smaller and lighter than many southern grey wolves.",
    behaviour: "Can hunt alone or in small packs, depending on prey availability and territory size.",
    bestSeason: "Late winter to summer, though sightings are very rare because of its remote habitat.",
    bestPlace: "Remote northern and northeastern Arctic areas.",
    funFact: "The Arctic wolf can survive in extremely remote areas where few other large predators can live.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-006",
    name: "Sæl (Ringsæl)",
    image: "Images/Images/animals/ringsael.png",
    category: "pattedyr",
    description: "Den mest almindelige sæl i Grønland",
    region: "Arctic",
    id: "ringsæl",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Arctic coastal waters, sea ice, fjords and areas with stable ice cover.",
    diet: "Fish, crustaceans and small marine animals.",
    size: "Usually around 50–110 kg.",
    behaviour: "Keeps breathing holes open in the ice and spends much of its life in cold Arctic waters.",
    bestSeason: "Spring and early summer, especially near sea ice and breathing holes.",
    bestPlace: "Ice-covered fjords, coastal waters and Arctic marine areas.",
    funFact: "The ringed seal gets its name from the light ring-shaped markings in its fur.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-007",
    name: "Hvalros",
    image: "Images/Images/animals/hvalros.png",
    category: "pattedyr",
    description: "Kendt for sine lange stødtænder",
    region: "Arctic",
    id: "hvalros",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Cold Arctic coastal waters, shallow sea areas, ice edges and rocky haul-out sites.",
    diet: "Mainly clams, mussels and other bottom-dwelling marine animals.",
    size: "Adult males can weigh over 1,000 kg.",
    behaviour: "Often rests in groups on ice or land and uses sensitive whiskers to find food on the seabed.",
    bestSeason: "Summer and autumn, when they may gather at coastal haul-out areas.",
    bestPlace: "Shallow Arctic waters, ice edges and remote coastal resting sites.",
    funFact: "Walruses use their long tusks to help pull themselves onto ice and to show dominance.",
    conservation: "Vulnerable"
  },
  {
	dexNumber: "ARC-008",
    name: "Narhval",
    image: "Images/Images/animals/narhval.png",
    category: "pattedyr",
    description: "Har en lang spiralformet tand",
    region: "Arctic",
    id: "narhval",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Deep Arctic waters, fjords, pack ice and cold marine areas around Greenland and Canada.",
    diet: "Fish, squid, shrimp and other deep-water prey.",
    size: "Usually around 4–5 meters long, not including the male's tusk.",
    behaviour: "Lives in groups and is known for deep dives under Arctic sea ice.",
    bestSeason: "Summer, when narwhals may enter fjords and coastal waters.",
    bestPlace: "Arctic fjords, deep cold waters and areas with seasonal sea ice.",
    funFact: "The narwhal's tusk is actually an elongated tooth that can grow several meters long.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-009",
    name: "Grønlandshval",
    image: "Images/Images/animals/gronlandshval.png",
    category: "pattedyr",
    description: "Kan blive over 200 år gammel",
    region: "Arctic",
    id: "grønlandshval",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Arctic and sub-Arctic waters, especially areas with sea ice and cold productive seas.",
    diet: "Zooplankton, small crustaceans and other tiny marine animals filtered through baleen plates.",
    size: "Can grow over 15 meters long and weigh many tonnes.",
    behaviour: "A slow-moving baleen whale adapted to life in icy waters.",
    bestSeason: "Spring and summer, depending on migration and ice conditions.",
    bestPlace: "Arctic waters, fjords and ice-edge areas where food is abundant.",
    funFact: "The bowhead whale is one of the longest-living mammals on Earth and may live for more than 200 years.",
    conservation: "Least Concern"
  },

  // Fugle
  {
	dexNumber: "ARC-010",
    name: "Jagtfalk",
    image: "Images/Images/animals/Jagtfalken.png",
    category: "birds",
    description: "Jagtfalken er en frygtindgydende jæger",
    region: "Arctic",
    id: "jagtfalk",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Arctic tundra, cliffs, mountains, coastal areas and open rocky landscapes.",
    diet: "Mainly birds such as ptarmigan, seabirds and smaller birds, but it may also take small mammals.",
    size: "The gyrfalcon is the largest falcon in the world, with a wingspan often around 110–160 cm.",
    behaviour: "A powerful and fast hunter that uses speed, strength and surprise to catch prey in open landscapes.",
    bestSeason: "Spring and summer, especially near nesting cliffs and areas with many birds.",
    bestPlace: "Mountain cliffs, tundra landscapes and coastal bird areas.",
    funFact: "The gyrfalcon can appear in different colour forms, from dark grey to almost completely white.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-011",
    name: "Havørn",
    image: "Images/Images/animals/Havorn.png",
    category: "birds",
    description: "Har et vingefang på 2,5 meter, og er Grønlands største fugl",
    region: "Arctic",
    id: "havørn",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Coastal cliffs, fjords and areas near open water.",
    diet: "Fish, seabirds, carrion and smaller animals.",
    size: "Wingspan up to around 2.5 meters.",
    behaviour: "Powerful bird of prey often seen soaring near coasts and fjords.",
    bestSeason: "Spring to autumn.",
    bestPlace: "Fjords, coastal cliffs and areas with access to fish.",
    funFact: "The white-tailed eagle is one of the largest birds of prey in northern Europe and Greenland.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-012",
    name: "Sneugle / Uppik",
    image: "Images/Images/animals/Sneugle.png",
    category: "birds",
    description: "Sneuglen kan svæve helt lydløst over sneen",
    region: "Arctic",
    id: "sneugle",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Open Arctic tundra, polar deserts, rocky areas and wide treeless landscapes.",
    diet: "Lemmings, small mammals, birds and other small prey.",
    size: "A large owl with a wingspan often around 125–150 cm.",
    behaviour: "A patient hunter that often sits on elevated ground and scans the open tundra for prey.",
    bestSeason: "Summer in Arctic breeding areas, though sightings can be unpredictable.",
    bestPlace: "Open tundra, rocky highlands and remote Arctic landscapes.",
    funFact: "Male snowy owls are often almost pure white, while females usually have more dark markings.",
    conservation: "Vulnerable"
  },
  {
	dexNumber: "ARC-013",
    name: "Vandrefalk / Kiinaaleeraq",
    image: "Images/Images/animals/vandrefalk.png",
    category: "birds",
    description: "Berømt for at være verdens hurtigste dyr. Der er målt en topfart på 350 km/t.",
    region: "Arctic",
    id: "vandrefalk",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Cliffs, mountains, coastal areas and open landscapes where prey birds are available.",
    diet: "Mostly birds caught in flight.",
    size: "Medium-sized falcon with a wingspan often around 80–120 cm.",
    behaviour: "Known for high-speed hunting dives where it strikes prey from above.",
    bestSeason: "Spring and summer, especially near nesting cliffs and bird-rich coastal areas.",
    bestPlace: "Cliffs, fjords, coastal bird areas and open hunting grounds.",
    funFact: "The peregrine falcon is often described as the fastest animal on Earth during its hunting dive.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-014",
    name: "Fjeldrype / Aqisseq",
    image: "Images/Images/animals/Fjeldrype.png",
    category: "birds",
    description: "Grønlands eneste hønsefugl",
    region: "Arctic",
    id: "fjeldrype",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Arctic tundra, rocky slopes, heathland and mountain areas.",
    diet: "Buds, leaves, berries, seeds and other low Arctic vegetation.",
    size: "A medium-sized ground bird, usually around 35–40 cm long.",
    behaviour: "Often stays close to the ground and uses camouflage to avoid predators.",
    bestSeason: "Spring to autumn, though it can be seen year-round in suitable areas.",
    bestPlace: "Open tundra, fjeld areas, rocky slopes and low vegetation zones.",
    funFact: "The ptarmigan changes plumage with the seasons, becoming white in winter for camouflage.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-015",
    name: "Ravn / Tulugaq",
    image: "Images/Images/animals/ravn.png",
    category: "birds",
    description: "Ravnen er verdens største kragefugl",
    region: "Arctic",
    id: "ravn",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Cliffs, mountains, settlements, coastlines, tundra and open landscapes.",
    diet: "Carrion, eggs, small animals, insects, berries and human food scraps.",
    size: "A large corvid with a wingspan often over 1 meter.",
    behaviour: "Highly intelligent, adaptable and often seen flying in pairs or searching for food.",
    bestSeason: "Year-round.",
    bestPlace: "Almost anywhere in Arctic regions, especially near cliffs, settlements and coastlines.",
    funFact: "Ravens are known for problem-solving, play behaviour and a wide range of calls.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-016",
    name: "Kongeedderfugl / Miteq Sioraki",
    image: "Images/Images/animals/kongeedderfugl.png",
    category: "birds",
    description: "Hannen har en farvestrålende yngledragt",
    region: "Arctic",
    id: "kongeedderfugl",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Arctic coastal waters, sea ice edges, tundra ponds and marine areas.",
    diet: "Molluscs, crustaceans, sea urchins and other small marine animals.",
    size: "A large sea duck, usually around 50–60 cm long.",
    behaviour: "Often gathers in flocks and dives underwater to feed on marine animals.",
    bestSeason: "Spring and summer during breeding season, and migration periods near coastlines.",
    bestPlace: "Arctic coastlines, fjords, sea ice edges and sheltered marine areas.",
    funFact: "Male king eiders have a striking colourful head pattern during breeding season.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-017",
    name: "Lomvie / Appa",
    image: "Images/Images/animals/Lomvie.png",
    category: "birds",
    description: "Lever i store kolonier på fuglefjelde",
    region: "Arctic",
    id: "lomvie",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Sea cliffs, bird colonies, coastal waters and open ocean areas.",
    diet: "Small fish, crustaceans and other marine prey.",
    size: "Usually around 38–46 cm long.",
    behaviour: "A strong diver that uses its wings to swim underwater while hunting fish.",
    bestSeason: "Summer, especially near breeding colonies on bird cliffs.",
    bestPlace: "Bird cliffs, rocky coastlines and productive marine areas.",
    funFact: "Young guillemots leave the cliff before they can fly properly and jump down toward the sea.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-018",
    name: "Tejst",
    image: "Images/Images/animals/Tejst.png",
    category: "birds",
    description: "Sort fugl med hvide vingefelter",
    region: "Arctic",
    id: "tejst",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Rocky coastlines, fjords, islands and cold northern marine areas.",
    diet: "Small fish, crustaceans and marine invertebrates.",
    size: "Usually around 30–35 cm long.",
    behaviour: "Dives underwater to catch food and often nests in rocky cracks or crevices.",
    bestSeason: "Spring and summer near breeding areas.",
    bestPlace: "Rocky coasts, small islands, fjords and sheltered marine areas.",
    funFact: "The black guillemot has bright red feet that stand out against its dark plumage.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "ARC-019",
    name: "Snespurv",
    image: "Images/Images/animals/Snespurv.png",
    category: "birds",
    description: "En af de nordligst ynglende småfugle",
    region: "Arctic",
    id: "snespurv",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Arctic tundra, rocky areas, settlements, coastlines and open landscapes.",
    diet: "Seeds, insects, small invertebrates and plant material.",
    size: "A small songbird, usually around 15–18 cm long.",
    behaviour: "Often seen hopping on the ground while searching for food in open areas.",
    bestSeason: "Spring and summer during the breeding season.",
    bestPlace: "Tundra, rocky slopes, settlements and open Arctic landscapes.",
    funFact: "The snow bunting is one of the northernmost breeding songbirds in the world.",
    conservation: "Least Concern"
  },
  // fisk
  {
	dexNumber: "ARC-020",
    name: "Torsk / Saarullik",
    image: "Images/Images/animals/Torsk.png",
    category: "fish",
    description: "Kan veje op til 15-30 kg.",
    region: "Arctic",
    id: "torsk",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Cold northern waters, coastal areas, fjords and deeper offshore zones.",
    diet: "Small fish, shrimp, crabs, worms and other marine animals.",
    size: "Can commonly weigh several kilograms, and large individuals may reach 15–30 kg.",
    behaviour: "A strong predatory fish that can live near the seabed as well as in open water.",
    bestSeason: "Spring to autumn, depending on local waters and fish movement.",
    bestPlace: "Fjords, coastal fishing areas and colder northern waters.",
    funFact: "Cod have a small barbel under the chin that helps them sense food near the seabed.",
    conservation: "Varies by stock"
  },
  {
	dexNumber: "ARC-021",
    name: "Stor rødfisk / Suluppaagaq",
    image: "Images/Images/animals/Rodfisk.png",
    category: "fish",
    description: "Stor mund med underbid og store øjne. Har 5 ugiftet pigge",
    region: "Arctic",
    id: "rødfisk",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Cold deep waters, rocky seabeds, continental slopes and offshore areas.",
    diet: "Small fish, shrimp, planktonic animals and other small marine prey.",
    size: "Can grow large and live for many decades.",
    behaviour: "Often lives in deeper water and moves slowly compared with many other fish.",
    bestSeason: "Year-round in deeper waters, depending on local fishing conditions.",
    bestPlace: "Deep cold waters around Greenland and the North Atlantic.",
    funFact: "Redfish have large eyes that help them see in deeper, darker water.",
    conservation: "Varies by stock"
  },
  {
	dexNumber: "ARC-022",
    name: "Hellefisk / Qaleralik",
    image: "Images/Images/animals/Hellefisk.png",
    category: "fish",
    description: "En vigtig eksportfisk fra Grønland",
    region: "Arctic",
    id: "hellefisk",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Cold deep waters, fjords, continental slopes and seabed areas.",
    diet: "Fish, shrimp, squid and other animals found near the seabed or in the water column.",
    size: "Can grow over 1 meter long.",
    behaviour: "A predatory flatfish that can swim actively in the water column, not only along the bottom.",
    bestSeason: "Year-round in many deep-water areas.",
    bestPlace: "Deep fjords and cold offshore waters around Greenland.",
    funFact: "Greenland halibut is one of Greenland's most important commercial fish species.",
    conservation: "Varies by stock"
  },
  {
	dexNumber: "ARC-023",
    name: "Laks",
    image: "Images/Images/animals/Laks.png",
    category: "fish",
    description: "Vandrer mellem hav og ferskvand",
    region: "Arctic",
    id: "artic-laks",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Rivers, freshwater systems, coastal waters and open sea during different life stages.",
    diet: "Insects and small aquatic animals as young fish; later small fish, shrimp and marine prey.",
    size: "Can vary greatly, but large salmon may weigh several kilograms.",
    behaviour: "Migrates between freshwater and the sea, often returning to freshwater to spawn.",
    bestSeason: "Summer and autumn, especially during migration periods.",
    bestPlace: "Rivers, river mouths and coastal waters where salmon migrate.",
    funFact: "Salmon can return from the ocean to the same river system where they were born.",
    conservation: "Varies by population"
  },
  
  //EUROPA
  // Pattedyr
  {
	dexNumber: "EUR-001",
    name: "Ulv",
    image: "Images/Images/europa/ulv.png",
    category: "pattedyr",
    description: "Et intelligent rovdyr, der lever i flokke.",
    region: "Europe",
    id: "ulv",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Forests, mountains, tundra, grasslands and remote rural landscapes.",
    diet: "Deer, wild boar, smaller mammals, carrion and occasionally livestock.",
    size: "Usually around 25–50 kg in Europe, though size varies by region.",
    behaviour: "Highly social predator that often lives and hunts in family groups called packs.",
    bestSeason: "Winter can make tracks easier to find, but sightings are rare year-round.",
    bestPlace: "Remote forests, mountain regions and wilderness areas with large prey animals.",
    funFact: "Wolves communicate with howls, scent marks, body language and facial expressions.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "EUR-002",
     name: "Grævling",
     image: "Images/Images/europa/grævling.png",
     category: "pattedyr",
     description: "Et kraftigt nataktivt rovdyr, der lever i underjordiske gangsystemer.",
     region: "Europe",
     id: "graevling",
     rarity: "uncommon",
     link: "learnmore.html",

     habitat: "Woodlands, hedgerows, farmland, meadows and countryside with soft soil for digging.",
     diet: "Earthworms, insects, fruit, roots, small mammals, eggs and carrion.",
     size: "Usually around 7–17 kg.",
     behaviour: "Mostly nocturnal and often lives in social groups in burrow systems called setts.",
     bestSeason: "Spring and summer evenings, when badgers may emerge before it is fully dark.",
     bestPlace: "Forest edges, old woodland, hedgerows and quiet rural areas.",
     funFact: "Badger setts can be used by generations of badgers for decades.",
     conservation: "Least Concern"
   },
  {
	dexNumber: "EUR-003",
    name: "Rådyr",
    image: "Images/Images/europa/rådyr.png",
    category: "pattedyr",
    description: "Et almindeligt hjortedyr i europæiske skove.",
    region: "Europe",
    id: "rådyr",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Forests, woodland edges, farmland, meadows, parks and mixed landscapes.",
    diet: "Leaves, buds, grasses, herbs, berries and agricultural crops.",
    size: "Usually around 15–35 kg.",
    behaviour: "Often shy and alert, usually active around dawn and dusk.",
    bestSeason: "Spring and summer, when roe deer are often seen feeding in open areas.",
    bestPlace: "Forest edges, fields, meadows and quiet rural roadsides.",
    funFact: "Roe deer fawns often lie hidden in tall grass while the mother feeds nearby.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "EUR-004",
    name: "Ræv",
    image: "Images/Images/europa/ræv.png",
    category: "pattedyr",
    description: "Et tilpasningsdygtigt rovdyr, der findes i mange landskaber.",
    region: "Europe",
    id: "ræv",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Forests, farmland, grasslands, suburbs, parks and coastal areas.",
    diet: "Small mammals, birds, eggs, insects, fruit, carrion and food scraps.",
    size: "Usually around 4–10 kg.",
    behaviour: "Clever, adaptable and often active at night or during twilight.",
    bestSeason: "Year-round, though spring and summer can offer more visible activity around dens.",
    bestPlace: "Woodland edges, fields, urban green spaces and quiet rural areas.",
    funFact: "Red foxes can hear small animals moving underground and may leap high before pouncing.",
    conservation: "Least Concern"
  },
  //FUGLE
  {
	dexNumber: "EUR-005",
    name: "Havørn",
    image: "Images/Images/europa/havorn.png",
    category: "birds",
    description: "En stor rovfugl med brede vinger og kraftigt næb.",
    region: "Europe",
    id: "havoern",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Coastal areas, lakes, wetlands, rivers and large forested landscapes near water.",
    diet: "Fish, waterbirds, carrion and occasionally small mammals.",
    size: "One of Europe’s largest birds of prey, with a wingspan that can exceed 2 meters.",
    behaviour: "Often seen soaring, perching near water or scanning open areas for prey.",
    bestSeason: "Winter and spring, when birds may be easier to spot near coastlines and lakes.",
    bestPlace: "Coastal cliffs, wetlands, large lakes and quiet areas with open water.",
    funFact: "White-tailed eagles are sometimes called flying barn doors because of their huge rectangular wings.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "EUR-006",
    name: "Rødhals",
    image: "Images/Images/europa/rødhals.png",
    category: "birds",
    description: "En lille fugl med orange bryst, ofte set i haver og skove.",
    region: "Europe",
    id: "roedhals",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Gardens, forests, hedgerows, parks and woodland edges.",
    diet: "Insects, worms, spiders, berries and small fruits.",
    size: "A small songbird, usually around 14 cm long.",
    behaviour: "Often bold around humans and known for its strong territorial song.",
    bestSeason: "Year-round, though it is especially noticeable in spring and winter.",
    bestPlace: "Gardens, forest paths, parks and hedgerows.",
    funFact: "Robins may follow gardeners to catch worms and insects disturbed in the soil.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "EUR-007",
    name: "Kirkeugle",
    image: "Images/Images/europa/kirkeugle.png",
    category: "birds",
    description: "En lys ugle med hjerteformet ansigt og næsten lydløs flugt.",
    region: "Europe",
    id: "kirkeugle",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Farmland, barns, old buildings, grasslands and open countryside.",
    diet: "Small mammals such as mice, voles and shrews.",
    size: "A medium-sized owl with long wings and a pale body.",
    behaviour: "Mostly nocturnal and hunts by flying low over open ground.",
    bestSeason: "Spring and summer evenings, when hunting activity can be easier to observe.",
    bestPlace: "Old barns, farmland, meadows and quiet rural roads.",
    funFact: "Barn owls can locate prey in complete darkness using extremely sensitive hearing.",
    conservation: "Least Concern"
  },
  // FISK
  {
	dexNumber: "EUR-008",
    name: "Laks",
    image: "Images/Images/europa/Laks.png",
    category: "fish",
    description: "En stærk vandrefisk, der bevæger sig mellem hav og ferskvand.",
    region: "Europe",
    id: "europe-laks",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Cold rivers, streams, estuaries and the North Atlantic Ocean.",
    diet: "Insects and small aquatic animals as juveniles; fish and crustaceans as adults.",
    size: "Can vary greatly, but large adults may weigh several kilograms.",
    behaviour: "Migrates from rivers to the ocean and later returns upstream to spawn.",
    bestSeason: "Late summer and autumn, depending on river system and migration timing.",
    bestPlace: "Clean, cold rivers with access to the sea.",
    funFact: "Salmon can return to the river where they were born by using smell and environmental cues.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "EUR-009",
    name: "Gedde",
    image: "Images/Images/europa/gedde.png",
    category: "fish",
    description: "En rovfisk med lang krop, skarpe tænder og eksplosive angreb.",
    region: "Europe",
    id: "gedde",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Lakes, slow rivers, canals, wetlands and weedy freshwater areas.",
    diet: "Fish, frogs, small birds and occasionally small mammals near the water.",
    size: "Can grow over 1 meter long in good conditions.",
    behaviour: "Ambush predator that waits hidden among vegetation before striking quickly.",
    bestSeason: "Spring and autumn, when pike are often more active in shallow waters.",
    bestPlace: "Reed beds, lake edges, slow rivers and areas with underwater vegetation.",
    funFact: "Pike can remain almost motionless before launching a sudden attack on prey.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "EUR-010",
    name: "Aborre",
    image: "Images/Images/europa/aborre.png",
    category: "fish",
    description: "En almindelig ferskvandsfisk med striber og pigget rygfinne.",
    region: "Europe",
    id: "aborre",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Lakes, rivers, ponds, reservoirs and brackish coastal waters.",
    diet: "Insects, larvae, small fish and aquatic invertebrates.",
    size: "Often small to medium-sized, but larger individuals can grow over 40 cm.",
    behaviour: "Often moves in groups and hunts smaller fish in clear or vegetated water.",
    bestSeason: "Summer and autumn, when perch are often active and easier to find.",
    bestPlace: "Lake edges, docks, reeds, rocky areas and slow-moving rivers.",
    funFact: "Perch often hunt in small groups, pushing prey fish into tighter schools.",
    conservation: "Least Concern"
  },
  
  //AFRIKA
  {
	dexNumber: "AFR-001",
    name: "Løve",
    image: "Images/Images/afrika/Lion.png",
    category: "pattedyr",
    description: "Et socialt rovdyr, kendt som savannens konge.",
    region: "Africa",
    id: "løve",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Savannas, grasslands, open woodlands and semi-arid landscapes.",
    diet: "Large herbivores such as antelope, zebra, wildebeest and buffalo.",
    size: "Adult males can weigh over 200 kg.",
    behaviour: "Highly social cat that lives in groups called prides, where females often do much of the hunting.",
    bestSeason: "Dry season, when animals gather around water sources and visibility is better.",
    bestPlace: "Savannas, national parks and open grassland areas with large prey populations.",
    funFact: "Lions are the only truly social big cats and can live in prides with several related females.",
    conservation: "Vulnerable"
  },
  {
	dexNumber: "AFR-002",
    name: "Giraf",
    image: "Images/Images/afrika/giraf.png",
    category: "pattedyr",
    description: "Verdens højeste landdyr.",
    region: "Africa",
    id: "giraf",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Savannas, open woodlands, dry forests and areas with acacia trees.",
    diet: "Leaves, shoots, flowers and fruits, especially from acacia trees.",
    size: "Can reach around 4.5–6 meters in height.",
    behaviour: "Usually moves calmly in loose groups and uses its long neck to browse high vegetation.",
    bestSeason: "Dry season, when visibility is good and animals gather near food and water.",
    bestPlace: "Savanna areas, open woodland and national parks with acacia vegetation.",
    funFact: "A giraffe's tongue can be around 45 cm long and helps it grab leaves from thorny branches.",
    conservation: "Vulnerable"
  },
  {
	dexNumber: "AFR-003",
    name: "Elefant",
    image: "Images/Images/afrika/elefant.png",
    category: "pattedyr",
    description: "Et af verdens største og mest intelligente landdyr.",
    region: "Africa",
    id: "elefant",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Savannas, forests, wetlands, grasslands and areas near water sources.",
    diet: "Grass, leaves, bark, fruit, roots and branches.",
    size: "African elephants can weigh several tonnes and are the largest land animals on Earth.",
    behaviour: "Highly intelligent and social, often living in family groups led by older females.",
    bestSeason: "Dry season, when elephants often gather near rivers and waterholes.",
    bestPlace: "National parks, savannas, river areas and woodland landscapes.",
    funFact: "Elephants can communicate using low-frequency sounds that travel over long distances.",
    conservation: "Endangered"
  },
  {
	dexNumber: "AFR-004",
    name: "Gepard",
    image: "Images/Images/afrika/gepard.png",
    category: "pattedyr",
    description: "Verdens hurtigste landdyr.",
    region: "Africa",
    id: "gepard",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Open savannas, grasslands, dry plains and lightly wooded areas.",
    diet: "Small to medium-sized antelope, hares and other fast-moving prey.",
    size: "Usually around 35–65 kg.",
    behaviour: "A specialised sprinter that relies on speed and stealth rather than strength.",
    bestSeason: "Dry season, when visibility is high and prey movement is easier to observe.",
    bestPlace: "Open grasslands, savannas and protected areas with healthy prey populations.",
    funFact: "Cheetahs can accelerate extremely quickly and are built for short bursts of speed rather than long chases.",
    conservation: "Vulnerable"
  },
  {
	 dexNumber: "AFR-005",
     name: "Flodhest",
     image: "Images/Images/afrika/flodhest.png",
     category: "pattedyr",
     description: "Et massivt semi-akvatisk pattedyr, der lever tæt på vand.",
     region: "Africa",
     id: "flodhest",
     rarity: "uncommon",
     link: "learnmore.html",

     habitat: "Rivers, lakes, wetlands and nearby grasslands.",
     diet: "Mostly grass, which it often grazes at night.",
     size: "Can weigh over 1,000 kg.",
     behaviour: "Spends much of the day in water and comes onto land at night to feed.",
     bestSeason: "Dry season, when hippos often gather in shrinking water sources.",
     bestPlace: "Rivers, lakes, wetlands and safari areas with permanent water.",
     funFact: "Hippos may look slow, but they can move surprisingly fast over short distances.",
     conservation: "Vulnerable"
   },
  {
	dexNumber: "AFR-006",
    name: "Struds",
    image: "Images/Images/afrika/struds.png",
    category: "birds",
    description: "Verdens største fugl, kendt for sin fart og lange ben.",
    region: "Africa",
    id: "struds",
    rarity: "common",
    link: "learnmore.html",

    habitat: "Savannas, dry grasslands, semi-deserts and open plains.",
    diet: "Seeds, grasses, leaves, flowers, insects and small animals.",
    size: "Can stand over 2 meters tall and weigh more than 100 kg.",
    behaviour: "Flightless bird that relies on speed, strong legs and alertness to avoid danger.",
    bestSeason: "Dry season, when visibility is better in open landscapes.",
    bestPlace: "Open savannas, grasslands and semi-arid plains.",
    funFact: "Ostriches have the largest eyes of any land animal.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "AFR-007",
    name: "Afrikansk fiskeørn",
    image: "Images/Images/afrika/fiskeørn.png",
    category: "birds",
    description: "En ikonisk rovfugl, ofte set nær søer og floder.",
    region: "Africa",
    id: "afrikansk-fiskeoern",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Lakes, rivers, wetlands, reservoirs and coastal lagoons.",
    diet: "Mostly fish, but also waterbirds, carrion and small animals.",
    size: "A large eagle with a broad wingspan and powerful talons.",
    behaviour: "Often perches near water before swooping down to catch fish.",
    bestSeason: "Dry season, when water sources attract more wildlife.",
    bestPlace: "Large lakes, rivers, wetlands and national parks with open water.",
    funFact: "Its call is one of the most recognizable sounds of many African waterways.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "AFR-008",
    name: "Sekretærfugl",
    image: "Images/Images/afrika/sekretærfugl.png",
    category: "birds",
    description: "En langbenet rovfugl, der jager på jorden.",
    region: "Africa",
    id: "sekretaerfugl",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Open grasslands, savannas and lightly wooded plains.",
    diet: "Snakes, lizards, insects, small mammals and birds.",
    size: "A tall bird of prey that can stand over 1 meter high.",
    behaviour: "Walks long distances while hunting and uses powerful kicks to subdue prey.",
    bestSeason: "Dry season, when grass is shorter and visibility is higher.",
    bestPlace: "Open savanna, protected grasslands and national parks.",
    funFact: "Secretarybirds are famous for hunting snakes by striking with their strong legs.",
    conservation: "Endangered"
  },
  {
	dexNumber: "AFR-009",
    name: "Nilaborre",
    image: "Images/Images/afrika/Nilaborre.png",
    category: "fish",
    description: "En stor rovfisk fra afrikanske søer og floder.",
    region: "Africa",
    id: "nilaborre",
    rarity: "uncommon",
    link: "learnmore.html",

    habitat: "Large lakes, rivers and deep freshwater systems.",
    diet: "Fish, crustaceans and aquatic animals.",
    size: "Can grow extremely large and weigh over 100 kg.",
    behaviour: "Powerful predator that often hunts in open or deeper freshwater areas.",
    bestSeason: "Dry season can make fishing and observation conditions easier in some areas.",
    bestPlace: "Large African lakes and river systems.",
    funFact: "The Nile perch is one of Africa’s largest freshwater fish.",
    conservation: "Least Concern"
  },
  {
	dexNumber: "AFR-010",
    name: "Tigerfisk",
    image: "Images/Images/afrika/tigerfisk.png",
    category: "fish",
    description: "En aggressiv rovfisk med skarpe tænder og stærke kæber.",
    region: "Africa",
    id: "tigerfisk",
    rarity: "rare",
    link: "learnmore.html",

    habitat: "Large rivers, lakes and fast-moving freshwater systems.",
    diet: "Mostly fish, but large individuals may attack a wide range of prey.",
    size: "Size varies by species, but some can become large and powerful predators.",
    behaviour: "Fast, aggressive and often hunts in turbulent water or open river channels.",
    bestSeason: "Dry season, when water levels may concentrate fish in certain areas.",
    bestPlace: "Major rivers, rapids, channels and large lakes.",
    funFact: "Tigerfish are known for their sharp, visible teeth and explosive strikes.",
    conservation: "Least Concern"
  },
 
   
];